/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'seanoneill' at '05/10/16 14:53' with Gradle 2.8
 *
 * @author seanoneill, @date 05/10/16 14:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String... args) {
        System.out.println("FOFOFOFOFO");
    }
}
