/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'seanoneill' at '05/10/16 14:27' with Gradle 2.8
 *
 * @author seanoneill, @date 05/10/16 14:27
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
